### ISSUE TITLE
build fails UIDevice+PasscodeStatus.h

### ISSUE THREAD

**Issue by adrai** [beast/react-native-isDeviceRooted#1]
I followed your installation instructions.
When I build my app I get following error:
/Users/usr/Projects/myapp/node_modules/react-native-is-device-rooted/ios/RNIsDeviceRooted.m:2:9: fatal error: 'UIDevice+PasscodeStatus.h' file not found
#import "UIDevice+PasscodeStatus.h"

What am I doing wrong?

PS. I'm a Javascript developer ;-)

**Comment by beast** [comment]
Sorry things have been crazy for my end. Did you happen to solve the issue? Thanks.

**Comment by adrai** [comment]
No, I don't need it anymore...

**Comment by Desintegrator** [comment]
same issue
