### ISSUE TITLE
Root check methods do not work on Android 7

### ISSUE THREAD

**Issue by eenchev** [beast/react-native-isDeviceRooted#2]
Hello,
I tried to incorporate the module into my app. However, all the 3 root method checks could not detect root. The devices I did the tests on are Samsung Galaxy S5 running LineageOS 14.1 and OnePlus 3T stock Android 7. I found another method checking if the device executes the "su" commands. Succssfully detected root on these two devices, as well as detected no root status on an unrooted Huawei P9 Lite running Android 6 stock. The Java native method used is below. I can make a pull request if you'd like.

```
private static boolean canExecuteSu() {
        boolean executedSuccesfully;
        try {
            Runtime.getRuntime().exec("su");
            executedSuccesfully = true;
        } catch (Exception e) {
            executedSuccesfully = false;
        }
        return executedSuccesfully;
  }
```

**Comment by beast** [comment]
@eenchev feel free to make the pull request and thanks in advance. Will add you to contributor section once pr is done.Thanks!
