### ISSUE TITLE
iOS: Unable to compile

### ISSUE THREAD

**Issue by gustavjf** [beast/react-native-isDeviceRooted#3]
Hi, I'm unable to successfully compile for iOS using `react-native run-ios` or via XCode 8.2.1.

```
/Users/me/dev/my_project/node_modules/react-native-is-device-rooted/ios/RNIsDeviceRooted.m:2:9: fatal error: 'UIDevice_PasscodeStatus.h' file not found
#import "UIDevice_PasscodeStatus.h"
^
1 error generated.



** BUILD FAILED **



The following build commands failed:
CompileC /Users/me/dev/my_project/ios/build/Build/Intermediates/RNIsDeviceRooted.build/Debug-iphonesimulator/RNIsDeviceRooted.build/Objects-normal/x86_64/RNIsDeviceRooted.o RNIsDeviceRooted.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

I went through the manual installation instructions for iOS and Android like so:

#### iOS:

I followed all steps as described except for the Podfile changes. I suspect this might be the culprit. My Podfile is roughly as follows:

```
target <NAME_OF_MY_PROJECT> do
 pod <some_dependency>
 pod <another_dependency>
 ...
 
 pod 'UIDevice-PasscodeStatus', '~> 0.0.2'
end
```

#### Android: Works fine.

I've tried the following:

1. Rename the import in `RNIsDeviceRooted.m` from `#import "UIDevice-PasscodeStatus.h"` to `#import "UIDevice_PasscodeStatus.h"`. I thought this was worth a shot because it showed up when clicking in XCode on `Project Navigator` > `MyProject` > `Libraries` > `RNIsDeviceRooted.xcodeproj` > `Build Phases` > `Link Binary with Libraries` > `UIDevice_PasscodeStatus.framework`.

2. Run `react-native link`

No luck so far. I'm not so familiar with native iOS development, perhaps I'm missing something common.

**Comment by beast** [comment]
@gustavjf Hi, there. iOS setup for the project is quite tricky because I am using a third party iOS package to respect the owner of that project. I suggest you look into https://github.com/GantMan/jail-monkey

Sorry I've been really busy with my work and have not had a chance to look after this repo for a while. Any help is appreciated.

**Comment by gustavjf** [comment]
Hi @beast, not a problem - I ended up checking out `jail-monkey` as you suggested. All good!
